services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: earlgrey
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres  # where to store data
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
