server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: earlgrey
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop    # destroy schema at the end of our session
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
